const fs = require('fs');
let html = fs.readFileSync('Create_Studio.html', 'utf-8');

const search = '})})],showAuth && k("div", {className: "fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm"}, [k("div", {className: "bg-white w-full max-w-md rounded-[24px] shadow-2xl overflow-hidden"}, [k("div", {className: "p-6 text-center border-b border-slate-100 relative"}, [m("button", {onClick: () => setShowAuth(!1), className: "absolute top-5 right-5 w-8 h-8 flex items-center justify-center rounded-full bg-slate-50 text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors text-[18px] leading-none pb-1"}, "✕"),m("div", {className: "w-12 h-12 rounded-2xl bg-violet-100 flex items-center justify-center mx-auto mb-4"}, m(Sr, {className: "w-6 h-6 text-violet-600"})),m("h2", {className: "text-[20px] font-bold text-slate-900"}, "Welcome to Vectra Studio"),m("p", {className: "text-[13px] text-slate-500 mt-2"}, "Log in or create an account to start your first project.")]),k("div", {className: "p-6 flex flex-col gap-4"}, [k("div", {className: "flex flex-col gap-1"}, [m("label", {className: "text-[11px] font-semibold text-slate-600 uppercase tracking-widest ml-1"}, "Email"),m("input", {type: "email", placeholder: "Enter your email", className: "h-11 px-4 rounded-xl border border-slate-200 bg-slate-50 text-[14px] outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100 transition-all"})]),k("div", {className: "flex flex-col gap-1"}, [m("label", {className: "text-[11px] font-semibold text-slate-600 uppercase tracking-widest ml-1"}, "Password"),m("input", {type: "password", placeholder: "••••••••", className: "h-11 px-4 rounded-xl border border-slate-200 bg-slate-50 text-[14px] outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100 transition-all"})]),m("button", {className: "h-11 mt-2 rounded-xl bg-violet-600 text-white text-[14px] font-semibold shadow-sm hover:bg-violet-700 transition-colors flex items-center justify-center"}, "Login / Create Account"),m("div", {className: "text-center mt-2 text-[12px] text-slate-500"}, ["By continuing, you agree to our ", m("a", {href:"#", className: "text-violet-600 hover:underline"}, "Terms"), " and ", m("a", {href:"#", className: "text-violet-600 hover:underline"}, "Privacy"), "."])])])]))}';

const replace = '})}),showAuth && k("div", {className: "fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm"}, [k("div", {className: "bg-white w-full max-w-md rounded-[24px] shadow-2xl overflow-hidden"}, [k("div", {className: "p-6 text-center border-b border-slate-100 relative"}, [m("button", {onClick: () => setShowAuth(!1), className: "absolute top-5 right-5 w-8 h-8 flex items-center justify-center rounded-full bg-slate-50 text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors text-[18px] leading-none pb-1"}, "✕"),m("div", {className: "w-12 h-12 rounded-2xl bg-violet-100 flex items-center justify-center mx-auto mb-4"}, m(Sr, {className: "w-6 h-6 text-violet-600"})),m("h2", {className: "text-[20px] font-bold text-slate-900"}, "Welcome to Vectra Studio"),m("p", {className: "text-[13px] text-slate-500 mt-2"}, "Log in or create an account to start your first project.")]),k("div", {className: "p-6 flex flex-col gap-4"}, [k("div", {className: "flex flex-col gap-1"}, [m("label", {className: "text-[11px] font-semibold text-slate-600 uppercase tracking-widest ml-1"}, "Email"),m("input", {type: "email", placeholder: "Enter your email", className: "h-11 px-4 rounded-xl border border-slate-200 bg-slate-50 text-[14px] outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100 transition-all"})]),k("div", {className: "flex flex-col gap-1"}, [m("label", {className: "text-[11px] font-semibold text-slate-600 uppercase tracking-widest ml-1"}, "Password"),m("input", {type: "password", placeholder: "••••••••", className: "h-11 px-4 rounded-xl border border-slate-200 bg-slate-50 text-[14px] outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100 transition-all"})]),m("button", {className: "h-11 mt-2 rounded-xl bg-violet-600 text-white text-[14px] font-semibold shadow-sm hover:bg-violet-700 transition-colors flex items-center justify-center"}, "Login / Create Account"),m("div", {className: "text-center mt-2 text-[12px] text-slate-500"}, ["By continuing, you agree to our ", m("a", {href:"#", className: "text-violet-600 hover:underline"}, "Terms"), " and ", m("a", {href:"#", className: "text-violet-600 hover:underline"}, "Privacy"), "."])])])])])}';

if (html.includes(search)) {
  html = html.replace(search, replace);
  fs.writeFileSync('Create_Studio.html', html);
  console.log("Successfully replaced the buggy syntax.");
} else {
  console.log("Search string not found!");
}
